export const inventoryData = {
  categories: [
    {
      name: "Grains & Staples",
      items: [
        "Sugar",
        "Jaggery",
        "Rice (Economy)",
        "Rice (Mid-Range)",
        "Rice (Premium)",
        "Flattened Rice (Poha)",
        "Gram Flour (Besan)",
        "Green Moong (Whole)",
        "Black Moong (Whole)",
        "Split Moong Dal",
        "Masoor Dal",
        "Toor/Arhar Dal",
        "Urad Dal",
        "Semolina (Suji)",
        "All-Purpose Flour (Maida)",
        "Powdered Sugar (Bura)",
        "Rock Candy (Mishri)",
        "Instant Noodles",
        "Dried Lentil Dumplings (Barri)",
        "Fenugreek Seeds (Methi Dana)",
        "Baking Soda",
        "Tomato Ketchup",
        "Asafoetida (Hing)",
        "Shaving Blade (RK)",
        "Shaving Blade (Gillette)",
      ],
    },
    {
      name: "Oils & Ghee",
      items: [
        "Amla Hair Oil (Mustard Base)",
        "Mustard Oil",
        "Amla Hair Oil (Shanti)",
        "Amla Hair Oil (Dabur)",
        "Coconut Oil",
        "Almond Hair Oil (Bajaj)",
        "Hair Oil (Haircare)",
        "Jasmine Hair Oil",
        "Cooling Hair Oil (Navratan)",
        "Refined Soyabean Oil",
        "Castor Oil",
        "Groundnut Oil",
        "Oil Pouch (500ml)",
        "Oil Pouch (800ml)",
        "Oil Pouch (900ml)",
        "Oil Can (2 Litre)",
        "Oil Can (5 Litre)",
        "Oil Tin (15 Litre)",
        "Vanaspati Ghee",
        "Pure Ghee (250g)",
        "Pure Ghee (500g)",
        "Pure Ghee (1kg)",
      ],
    },
    {
      name: "Snacks & Savories",
      items: [
        "Potato Chips (Spicy)",
        "Puffed Rings",
        "Pop Corn",
        "Cumin Papad (Jeera Papad)",
        "Puffed Corn Snack (Light)",
        "Cup Noodles",
        "Snack with Ketchup",
        "Puffed Corn Snack (Papa Ki Pari)",
        "Puffed Corn Curls (Tedhe Medhe)",
        "Corn Mixture",
        "Puffed Snack (Bubbles)",
        "Puffed Corn Snack (Salman Khan)",
        "Orange Corn Puffs",
        "Puffed Corn Snack (Doremon)",
        "Pen-shaped Puffed Snack (Refill)",
        "Sev Samosa",
        "Sev (Akash)",
        "Hing Chana (Akash)",
        "Aloo Bhujia (Akash)",
        "Fasting Mixture (Akash)",
        "Tasty Peanuts (Akash)",
        "Sweet & Sour Mixture (Akash)",
        "Moong Dal Namkeen (Akash)",
        "Potato Bites (Akash)",
        "Fried Noodles Snack (Akash)",
        "Spicy Mixture (Akash)",
        "Sev Puffed Rice (Akash)",
        "Green Peas Namkeen (Akash)",
        "Sev (Shayamji)",
        "Sev (Girraj ji)",
        "Sev (Bajrang)",
        "Sev (Medium)",
        "Sev (Thick)",
        "Bhujia",
        "Gathiya",
        "Fasting Dal Mixture",
        "Sweet Mixture",
        "Spicy Peanuts (Chirpo)",
        "Fried Peanuts",
        "Green Peas (Fried)",
        "Potato Wafers",
        "Boondi",
        "Mixture",
        "Sev (Akash 400g)",
        "Sev (₹30 Pack)",
        "Papad (₹10 Pack)",
        "Papad (₹20 Pack)",
        "Papad Pieces",
        "Fryums (Punga)",
        "Fryum Pieces",
      ],
    },
    {
      name: "Biscuits & Cookies",
      items: [
        "Biscuits (Patanjali)",
        "Glucose Biscuits (Parle-G)",
        "Biscuits (20-20)",
        "Cream Biscuits (Subisco)",
        "Chocolate Cream Biscuits (CNC)",
        "Cream Biscuits (Magix)",
        "Cream Biscuits (Sunfeast Bounce)",
        "Biscuits (Monaco)",
        "Sweet Puffs (Tosh Latkan)",
        "Biscuits (Prabhat ₹10)",
        "Biscuits (Prabhat ₹20)",
        "Special Rusk",
        "Assorted Biscuits (₹50 Pack)",
      ],
    },
    {
      name: "Chocolates & Candies",
      items: [
        "Eclairs",
        "Raw Mango Candy",
        "Eclairs (Local)",
        "Coconut Candy",
        "Pulse Candy",
        "Jelly Candy",
        "Chocolate Candy (Coco)",
        "Hajmola",
        "Sweet Balls (Ladoo)",
        "Lollipop",
        "Center Fresh",
        "Center Fruit",
        "Dairy Milk Chocolate",
        "Five Star Chocolate",
        "Snickers Chocolate",
        "Kit Kat Chocolate",
        "Toy Candy",
        "Dairy Milk Chocolate (₹2)",
        "Tamarind Candy (Imli)",
        "Sonpapdi",
        "Milk Cake (Barfi)",
        "Milk Candy",
        "Orange Candy",
        "Gajak",
        "Balloon",
      ],
    },
    {
      name: "Spices & Masalas",
      items: [
        "Red Chilli Powder (₹10 Pack)",
        "Red Chilli Powder (₹25 Pack)",
        "Red Chilli Powder (₹50 Pack)",
        "Red Chilli Powder (500g)",
        "Kashmiri Red Chilli Powder",
        "Whole Red Chillies",
        "Turmeric Powder (₹10 Pack)",
        "Turmeric Powder (₹25 Pack)",
        "Turmeric Powder (₹50 Pack)",
        "Turmeric Powder (500g)",
        "Coriander Powder (₹10 Pack)",
        "Coriander Powder (₹20 Pack)",
        "Coriander Powder (₹50 Pack)",
        "Coriander Powder (500g)",
        "Salt",
        "Rock Salt (Sendha Namak)",
        "Whole Salt Crystals",
        "Whole Black Salt",
        "Blended Spices (Pushp)",
        "Blended Spices (Neelam ₹20)",
        "Blended Spices (Neelam ₹50)",
        "Whole Spices Mix (₹10-₹20)",
        "Loose Spices",
        "Black Pepper",
        "Cumin Seeds (Jeera)",
        "Carom Seeds (Ajwain)",
        "Fennel Seeds (Saunf)",
        "Sesame Seeds (Tilli)",
        "Lotus Seeds (Kamal Gatta)",
        "Licorice (Mulathi)",
        "Long Pepper (Peepar)",
        "Ganthoda (Peepramur)",
        "Raita Masala",
        "Dried Fenugreek Leaves (Kasturi Methi)",
        "Chana Masala",
        "Pasta Masala",
        "Maggie Masala",
        "Paneer Masala",
        "Pickle Masala",
      ],
    },
    {
      name: "Pooja Essentials",
      items: [
        "Incense Sticks (₹5 Pack)",
        "Incense Sticks (₹10 Pack)",
        "Incense Sticks (Kashi)",
        "Mosquito Repellent Incense",
        "Incense Sticks (₹20 Pack)",
        "Incense Sticks (₹50 Pack)",
        "Dhoop Batti",
        "Dry Fruits Mix (Panchmeva)",
        "Coconut (Dry)",
        "Loban",
        "Sindoor",
        "Betel Leaf (Pan)",
        "Betel Nut (Supari)",
        "Cardamom (Elaichi)",
        "Perfume Oil (Atar)",
        "Roli",
        "Bhoj Patra",
        "Chironji",
        "Havan Samagri Mix",
        "Chickpeas",
        "Red & White Cloth",
        "Cotton Wick (Aathi)",
        "Pooja Almonds",
        "Whole Betel Nut",
        "Cloves (Long)",
        "Mata Ki Pudiya",
        "Camphor (Kapoor)",
        "Saffron (Kesar)",
        "Fox Nuts (Makhane)",
        "Puffed Rice (Parmal)",
        "Barley (Joo)",
        "Dried Coconut Half (Khopda)",
        "Dessicated Coconut",
        "Dried Coconut Whole (Gola)",
        "Sago (Sabudana)",
        "Amaranth Seeds (Mordana)",
        "Amaranth Flour (Rajgira)",
        "Water Chestnut Flour (Singhada)",
        "Cotton Roll",
        "Red & White Flag",
        "Sacred Thread (Janeu)",
        "Yellow Flag",
        "Green Flag",
        "Raw Cotton Thread",
        "Five-Colored Thread",
      ],
    },
    {
      name: "Personal Care",
      items: [
        "Soap (Lux ₹10)",
        "Soap (Lifebuoy)",
        "Soap (No. 1)",
        "Soap (Superia)",
        "Soap (Dettol ₹10)",
        "Neem Soap (₹10)",
        "Soap (Patanjali ₹10)",
        "Shampoo (Clinic Plus)",
        "Shampoo (Vatika)",
        "Shampoo (Patanjali)",
        "Shampoo (Dove)",
        "Shampoo (Head and Shoulders)",
        "Conditioner (Dove)",
        "Shampoo (Chick)",
        "Toothpaste (Patanjali ₹10)",
        "Toothpaste (Patanjali ₹20)",
        "Toothpaste (Patanjali ₹60)",
        "Toothpaste (Colgate ₹10)",
        "Toothpaste (Colgate ₹20)",
        "Toothpaste (Colgate ₹70)",
        "Toothpaste (Vicco)",
        "Toothpaste (Closeup ₹10)",
        "Toothpaste (Closeup ₹20)",
        "Toothpaste (Maxfresh ₹10)",
        "Toothpaste (Maxfresh ₹20)",
        "Toothpowder",
        "Toothbrush (₹10)",
        "Toothbrush (₹20)",
        "Toothbrush (₹40)",
        "Black Hair Dye",
        "Red Hair Dye",
        "Henna Cone (₹5)",
        "Instant Henna",
      ],
    },
    {
      name: "Cleaning Supplies",
      items: [
        "Dishwash Bar (₹5)",
        "Dishwash Bar (₹10)",
        "Laundry Bar (₹5)",
        "Laundry Bar (₹10)",
        "Detergent Powder (₹5 Pack)",
        "Detergent Powder (₹10 Pack)",
        "Detergent Powder (₹1 Pack)",
        "Detergent Powder (Sikha)",
        "Detergent Powder (Mor 1 Kg)",
        "Scrub Pad",
      ],
    },
    {
      name: "Tobacco & Pan Masala",
      items: [
        "Cigarette (Mid Land)",
        "Cigarette (Gold)",
        "Cigarette (Foursquare)",
        "Cigarette (Steller)",
        "Cigarette (Gold Flake)",
        "Cigarette (Mint)",
        "Cigarette (American)",
        "Chewing Tobacco (Jarda)",
        "Tobacco Leaves",
        "Betel Nut (Supari)",
        "Aged Betel Nut",
        "Bhang Goli",
        "Pan Masala (Rajshree ₹10)",
        "Pan Masala (Rajshree ₹20)",
        "Pan Masala (Rajshree ₹40)",
        "Pan Masala (Tansen ₹20)",
        "Pan Masala (Paheli ₹10)",
        "Pan Masala (Paheli ₹20)",
        "Pan Masala (Hamraj ₹10)",
        "Pan Masala (Vimal ₹5)",
        "Pan Masala (Vimal ₹10)",
        "Pan Masala (Vimal ₹20)",
        "Pan Masala (Nakhrali)",
        "Pan Masala (Masoom)",
        "Pan Masala (Ritik Gold)",
        "Pan Masala (Nakharli Green)",
      ],
    },
    {
      name: "Stationery",
      items: [
        "Pen - Blue (₹3)",
        "Pen - Red (₹3)",
        "Pen - Black (₹3)",
        "Pen - Blue (₹5)",
        "Pen - Black (₹5)",
        "Pen - Red (₹5)",
        "Pen - Retractable (₹10)",
        "Pen - Stick (₹10)",
        "Notebook (₹10)",
        "Notebook - 3 Subject (₹10)",
        "Notebook - English (₹10)",
        "Notebook - Math (₹10)",
        "Notebook (₹20)",
        "Notebook - 3 Subject (₹20)",
        "Notebook - English (₹20)",
        "Notebook - Math (₹20)",
        "Rough Register",
        "Pencil (₹5)",
        "Ruler (Scale)",
        "Carbon Paper",
        "Crayons",
        "Pencil Colors",
        "Sketch Pens",
        "Sharpener",
        "Eraser",
        "White Tape",
        "Black Tape",
        "Stapler",
        "Glue (Fevicol)",
        "Super Glue (Feviquick)",
      ],
    },
    {
      name: "Electronics & Hardware",
      items: [
        "LED Bulb",
        "Bulb (₹10)",
        "Batteries (AA/AAA)",
        "Battery Pack",
        "Electrical Wire (₹5)",
        "Electrical Wire (₹10)",
        "Plug Top",
        "Bulb Holder (₹10)",
        "Switch",
      ],
    },
    {
      name: "Kitchen & Disposables",
      items: [
        "Plastic Bag (8x10)",
        "Plastic Bag (9x13)",
        "Plastic Bag (11x14)",
        "Milk Pouch Bag",
        "Plastic Bag (500g capacity)",
        "Plastic Bag (1kg capacity)",
        "Plastic Bag (2kg capacity)",
        "Plastic Bag (3kg capacity)",
        "Plastic Bag (5kg capacity)",
        "Disposable Bowl (Small)",
        "Disposable Bowl (Medium)",
        "Disposable Bowl (Thermocol)",
        "Disposable Plate",
        "Disposable Tea Cup",
        "Disposable Water Glass",
      ],
    },
    {
      name: "Dry Fruits",
      items: [
        "Cashews",
        "Raisins",
        "Large Raisins (Munnaka)",
        "Almonds",
        "Achar Chironji",
        "Pistachios",
        "Dry Dates",
      ],
    },
    {
      name: "Tea & Coffee",
      items: [
        "Tea Leaves (₹5 Pack)",
        "Tea Leaves (₹10 Pack)",
        "Tea Leaves (₹50 Pack)",
        "Tea Leaves (250g)",
        "Tea Leaves (500g)",
        "Coffee (₹10 Sachet)",
      ],
    },
    {
      name: "Miscellaneous",
      items: [
        "Matchbox (₹1)",
        "Matchbox (₹2)",
        "Broom",
        "Needle",
        "Needle & Thread",
        "Blue Indigo (Neil)",
        "Glass Beads (Mohra)",
        "Rope (Jeuda)",
        "Harre",
        "Dhori Musri",
      ],
    },
    {
      name: "Basic Health & First Aid",
      items: [
        "Medicated Soap",
        "Antiseptic Liquid",
        "Fever/Pain Tablet (₹1 Pack)",
        "Fever/Pain Tablet (₹5 Pack)",
        "Anti-diarrhea Tablets",
        "Vicks Vaporub",
        "Adhesive Bandage (Band-Aid)",
      ],
    },
  ],
};

export default inventoryData;